#!/usr/bin/env bash
if [ $1 ]
then
    sudo update-alternatives --set php /usr/bin/php$1
    sudo nginx -s stop
    sudo nginx
    sudo service php7.4-fpm stop
    sudo service php8.0-fpm stop
    sudo service php$1-fpm start
    php -i | grep "Loaded Configuration File"
else
    echo "Please specify version"
fi
